### PR TITLE
Add .NET Core 3.0 support (fixes #1)

### LINKED ISSUE #1: .NET Core 3.0 Support
I want to add ASP.NET Core 3.0 Support to this project, i will send a PR. We can discuss on this.

### PR DESCRIPTION
**Pull request by sadedil**
## Change list

I've added .NET Core 3.0 support.
Linquest.AspNetCore project now supports multiple frameworks `netstandard2.0` and `netcoreapp3.0`.
 
## Types of changes

What types of changes are you proposing/introducing?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

- There is no breaking changes except one little point. I want to discuss this part in the comments.
- I've updated the *appveyor.yml* to use *Visual Studio 2019* image and increased the version to 3.0.
- By the way I've used the Rider IDE on Mac. Maybe line endings or formattings differs from your version :/

### CODE REVIEW

**Comment by umutozel** [comment]
Hi Mustafa (we are old colleagues), how are you?

PR looks great, but I have just one question.
Do you think we should do a major version change? I realized that there won't be any breaking change with .Net Core 3.0 support.

But aligning with major .Net Core version looks good though :)

**Comment by sadedil** [comment]
Hi Umut, I'm OK. I hope you are OK too :)

Yes you are right. Also I think we don't need the major version change. I guess I'm influenced by the .NET Core 3.0, EF Core 3.0 fashion.

If it's OK, I can update the version to `2.1`?

**Comment by umutozel** [comment]
I'm fine too, thank you :)

Yeah, .Net Core version is tempting, but Microsoft will release major versions regularly (like Angular did), so we won't be able to keep up with them anyway (and we shouldn't).

I'm merging your PR on a local PC right now, I can do the change. Thanks again 💯

**Comment by umutozel** [comment]
Published 2.1.1 to NuGet.

**Pull request merged**
